# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Body', models.TextField()),
                ('Date', models.DateTimeField()),
                ('Dislikes', models.IntegerField()),
                ('Likes', models.IntegerField()),
                ('Nbr_views', models.IntegerField()),
            ],
        ),
    ]
