# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_article_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Author',
            field=models.CharField(default='Your name', max_length=100),
        ),
    ]
